import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'cancelCode'
})
export class CancelCodePipe implements PipeTransform {

  transform(value: any, args?: any): any {
    let reason = 'Unknown Reason';

    switch (value) {
      case'AA': reason = `Waiting acceptance into off Network Terminal or Yard`;
                break;
      case'AC': reason = `Waiting train preparation or completion of TOPS list/RT3973`;
                break;
      case'AD': reason = `Off Network Terminal or Yard staff shortage including reactionary congestion caused by the shortage`;
                break;
      case'AE': reason = `Congestion in off Network Terminal or Yard`;
                break;
      case'AG': reason = `Wagon load incident including adjusting loads or open door`;
                break;
      case'AH': reason = `Customer or off Network yard equipment breakdown/reduced capacity`;
                break;
      case'AJ': reason = `Waiting Customer’s traffic including documentation`;
                break;
      case'AK': reason = `Safety incidents and mishaps (e.g. derailments, fire or chemical spill) in off Network Rail network freight yard or terminal (including private sidings, and stations – where it affects FOC services)`;
                break;
      case'AX': reason = `Failure of off network infrastructure (FOC or private)`;
                break;
      case'AZ': reason = `Other Freight Operating Company. Cause to be specified, including mishaps in off Network terminals or yards`;
                break;
      case'DA': reason = `Non Technical Fleet Holding Code`;
                break;
      case'DB': reason = `Train Operations Holding Code`;
                break;
      case'DC': reason = `Train Crew Causes Holding Code`;
                break;
      case'DD': reason = `Technical Fleet Holding Code`;
                break;
      case'DE': reason = `Station Causes Holding Code`;
                break;
      case'DF': reason = `External Causes Holding Code`;
                break;
      case'DG': reason = `Freight Terminal and or Yard Holding Code`;
                break;
      case'DH': reason = `Adhesion and or Autumn Holding Code`;
                break;
      case'FA': reason = `Dangerous goods incident`;
                break;
      case'FC': reason = `Freight train driver`;
                break;
      case'FE': reason = `Train crew not available`;
                break;
      case'FG': reason = `Driver adhering to company professional driving standards or policy`;
                break;
      case'FH': reason = `Planning issues including loco diagrams or RT3973 restriction not requested`;
                break;
      case'FI': reason = `Delay due to incorrect ETCS system or equipment operation by Driver`;
                break;
      case'FJ': reason = `Train held at FOC request`;
                break;
      case'FK': reason = `Train diverted or re-routed at FOC request`;
                break;
      case'FL': reason = `Train cancelled at FOC request or planned not to run`;
                break;
      case'FM': reason = `Tail lamp/head lamp out or incorrectly shown`;
                break;
      case'FN': reason = `Late presentation from Europe`;
                break;
      case'FO': reason = `Time lost en-route believed to be Operator cause and information required from Operator (Ops Responsibility)`;
                break;
      case'FP': reason = `Incorrect route taken or route wrongly challenged by driver, including SPAD's`;
                break;
      case'FS': reason = `Delay due to ETCS/ ERTMS on-board overriding driver command`;
                break;
      case'FT': reason = `Freight Operator autumn-attribution Neutral Zone delays`;
                break;
      case'FW': reason = `Late start or yard overtime not explained by Train Operator`;
                break;
      case'FX': reason = `Freight train running at lower class or speed than planned classification or overweight`;
                break;
      case'FZ': reason = `Other FOC causes incl. FOC control directive, cause to be specified, including mishaps.`;
                break;
      case'I0': reason = `Telecom equipment failures legacy (inc. NRN/CSR/RETB link)`;
                break;
      case'I1': reason = `Overhead line/third rail defect`;
                break;
      case'I2': reason = `AC/DC trip`;
                break;
      case'I4': reason = `OHL/third rail power supply failure or reduction`;
                break;
      case'I5': reason = `Possession over-run from planned work`;
                break;
      case'I6': reason = `Delays as a result of line blocks / track patrols`;
                break;
      case'I7': reason = `Engineer's train late or failed in possession`;
                break;
      case'I8': reason = `Animal Strike/Incursion within the control of Network Rail`;
                break;
      case'I9': reason = `Fires starting on Network Rail Infrastructure`;
                break;
      case'IA': reason = `Signal failure`;
                break;
      case'IB': reason = `Points failure`;
                break;
      case'IC': reason = `Track circuit failure`;
                break;
      case'ID': reason = `Level crossing failure incl. barrow/foot crossings and crossing treadles`;
                break;
      case'IE': reason = `Signalling functional power supply failure`;
                break;
      case'IF': reason = `Train Describer/Panel/ARS/SSI/TDM/Remote Control failure`;
                break;
      case'IG': reason = `Block failure`;
                break;
      case'IH': reason = `Power supply and distribution system failure`;
                break;
      case'II': reason = `Signalling lineside cable fault`;
                break;
      case'IJ': reason = `AWS/ATP/TPWS/Train Stop/On-track equipment failure`;
                break;
      case'IK': reason = `Telephone equipment failure`;
                break;
      case'IL': reason = `Token equipment failure`;
                break;
      case'IM': reason = `Infrastructure Balise Failure (TASS / ETCS / ERTMS)`;
                break;
      case'IN': reason = `HABD/Panchex/WILD/Wheelchex`;
                break;
      case'IP': reason = `Points failure caused by snow or frost where heaters are fitted but found to be not operative or defective`;
                break;
      case'IQ': reason = `Trackside sign blown down, missing, defective, mis-placed`;
                break;
      case'IR': reason = `Broken/cracked/twisted/buckled/flawed rail`;
                break;
      case'IS': reason = `Track defects (other than rail defects i.e. fish plates, wet beds etc)`;
                break;
      case'IT': reason = `Rough ride or bumps reported - cause not known`;
                break;
      case'IV': reason = `Earthslip/subsidence/breached sea defences (not the result of severe weather on the day of failure)`;
                break;
      case'IW': reason = `Non severe weather - snow/ice/frost affecting infrastructure equipment`;
                break;
      case'IZ': reason = `Other infrastructure causes`;
                break;
      case'J0': reason = `Telecom radio failures IVRS/GSM-R`;
                break;
      case'J2': reason = `Network Rail train dispatch equipment failure excluding telecoms equipment`;
                break;
      case'J3': reason = `Axle Counter Failure`;
                break;
      case'J4': reason = `Infrastructure Safety Issue Reported by Member of the Public – No Fault Found`;
                break;
      case'J5': reason = `Infrastructure Fault Report Proven to be mistaken`;
                break;
      case'J6': reason = `Lightning strike against unprotected assets`;
                break;
      case'J7': reason = `ETCS/ ERTMS Equipment Failure (excluding communications link and balises)`;
                break;
      case'J8': reason = `Damage to infrastructure caused by on-track machine whilst operating in a possession`;
                break;
      case'J9': reason = `Preventative Maintenance to the infrastructure in response to a Remote Condition Monitoring Alert`;
                break;
      case'JA': reason = `TSR speeds for Track-work outside the Rules of the Route`;
                break;
      case'JB': reason = `Reactionary Delay to 'P' coded TSR`;
                break;
      case'JD': reason = `Structures - Bridges/tunnels/buildings/ embankments (not bridge strikes)`;
                break;
      case'JG': reason = `ESR/TSR due to works not completed or cancelled possession (where restriction did not exist prior to possession)`;
                break;
      case'JH': reason = `Critical Rail Temperature speeds, (other than buckled rails)`;
                break;
      case'JK': reason = `Flooding not due to exceptional weather`;
                break;
      case'JL': reason = `Network Rail staff oversight or error (Maintenance / Infrastructure)`;
                break;
      case'JP': reason = `Failure to maintain vegetation within network boundaries in accordance with prevailing Network Rail standards, including where signals are obscured and a train strikes branches.`;
                break;
      case'JR': reason = `Delay due to RBC issues affecting ETCS / ATO operation (not balise related)`;
                break;
      case'JS': reason = `Condition of Track TSR outside the Timetable Planning Rules`;
                break;
      case'JT': reason = `Points failure caused by snow or frost where heaters are not fitted`;
                break;
      case'JX': reason = `Miscellaneous items (including trees) causing obstructions, not the result of trespass, vandalism, weather or fallen/thrown from trains`;
                break;
      case'M0': reason = `Confirmed train cab based safety system fault (including GSM-R)`;
                break;
      case'M1': reason = `Confirmed Pantograph ADD, shoe beam or assoc.system faults Incl. positive PANCHEX activations`;
                break;
      case'M2': reason = `Delay due to ATO / ETCS equipment`;
                break;
      case'M7': reason = `Door and Door system faults`;
                break;
      case'M8': reason = `Other technical failures above the Solebar`;
                break;
      case'M9': reason = `Reported fleet equipment defect - no fault found`;
                break;
      case'MB': reason = `Electric loco failure, defect, attention.`;
                break;
      case'MC': reason = `Diesel loco failure, defect, attention.`;
                break;
      case'MD': reason = `Other technical failures below the solebar`;
                break;
      case'ME': reason = `Steam locomotive failure/defect/attention`;
                break;
      case'MF': reason = `International/Channel Tunnel locomotive failure/defect/attention`;
                break;
      case'ML': reason = `Wagons, coaches and parcel vehicle faults`;
                break;
      case'MN': reason = `Brake and brake systems faults; including wheel flats where no other cause had been identified`;
                break;
      case'MP': reason = `Rail / wheel interface, adhesion problems (including ice on the running rail)`;
                break;
      case'MR': reason = `Sanders and scrubber faults`;
                break;
      case'MS': reason = `Planned underpowered or shortformed service and or vehicle, incl. exam set swaps`;
                break;
      case'MT': reason = `Confirmed train borne safety system faults (not cab based)`;
                break;
      case'MU': reason = `Depot operating problem`;
                break;
      case'MV': reason = `EngineerÕs on-track equipment failure outside possession`;
                break;
      case'MW': reason = `Weather - effect on T&RS equipment`;
                break;
      case'MY': reason = `Coupler and Coupler system faults`;
                break;
      case'NA': reason = `On-train TASS/TILT failure`;
                break;
      case'OA': reason = `Regulation decision made with best endeavours`;
                break;
      case'OB': reason = `Delayed by signaller not applying applicable regulating policy`;
                break;
      case'OC': reason = `Signaller, including wrong routing and wrong ETCS/ ERTMS instruction`;
                break;
      case'OD': reason = `Delayed as a result of Route Control decision or directive`;
                break;
      case'OE': reason = `Failure to lay Sandite or operate Railhead Conditioning train as programmed`;
                break;
      case'OF': reason = `Delay due to incorrect ETCS system or equipment operation by Signaller / Controller`;
                break;
      case'OG': reason = `Ice on conductor rail/OLE`;
                break;
      case'OH': reason = `ARS software problem (excluding scheduling issues and technical failures)`;
                break;
      case'OI': reason = `Formal Inquiry Incident - other operators`;
                break;
      case'OJ': reason = `Fire in station building or on platform, affecting operators not booked to call at that station`;
                break;
      case'OK': reason = `Delay caused by Operating staff oversight, issues or absence (excluding signallers and Control)`;
                break;
      case'OL': reason = `Signal Box not open during booked hours`;
                break;
      case'OM': reason = `Technical failure associated with a Railhead Conditioning train`;
                break;
      case'ON': reason = `Delays not properly investigated by Network Rail`;
                break;
      case'OP': reason = `Failure of TRUST or SMART system preventing recording and investigation of delay`;
                break;
      case'OQ': reason = `Incorrect Simplifier (where produced by Ops staff)`;
                break;
      case'OS': reason = `Late start or delays to Railhead Conditioning Train (RHC) including any reactionary delay to other trains`;
                break;
      case'OU': reason = `Delays not investigated by Network Rail`;
                break;
      case'OV': reason = `Fire or evacuation due to fire alarm of Network Rail buildings other than stations not due to vandalism`;
                break;
      case'OW': reason = `Connections held where the prime incident causing delay to the incoming train is a FOC owned incident and service is more frequent than hourly`;
                break;
      case'OZ': reason = `Other Network Rail Operating causes`;
                break;
      case'PA': reason = `TSR within Timetable Planning Rules`;
                break;
      case'PB': reason = `Condition of asset TSR within Engineering Access Statement (EAS)`;
                break;
      case'PD': reason = `TPS cancellation (Not to be input in TSI/TRUST)`;
                break;
      case'PE': reason = `Cancelled due to planned engineering work`;
                break;
      case'PF': reason = `Planned engineering work - diversion/SLW not timetabled (within Rules of the Route)`;
                break;
      case'PG': reason = `Planned cancellation by Train Operator including Bank Holiday schedules`;
                break;
      case'PJ': reason = `Cancellation of a duplicate or erroneous schedule or associated duplicate delay`;
                break;
      case'PL': reason = `Exclusion agreed between Network Rail and Train Operator`;
                break;
      case'PN': reason = `VSTP service delays of under 5 minutes caused by regulation and or time lost in running.`;
                break;
      case'PT': reason = `TRUST Berth Offset inaccuracies`;
                break;
      case'PZ': reason = `Other contractual exclusion`;
                break;
      case'QA': reason = `WTT Schedule and or LTP process including incorrect simplifiers (where produced by Capacity Planning).`;
                break;
      case'QB': reason = `Planned engineering work - diversion/SLW not timetabled (outside the Timetable Planning Rules.)`;
                break;
      case'QH': reason = `Adhesion problems due to leaf contamination`;
                break;
      case'QI': reason = `Cautioning due to railhead leaf contamination`;
                break;
      case'QJ': reason = `Special working for leaf-fall track circuit operation`;
                break;
      case'QM': reason = `Train Schedule VAR/STP process including incorrect simplifiers (where produced by Capacity Planning).`;
                break;
      case'QN': reason = `VSTP schedule / VSTP process (TSI created schedule)`;
                break;
      case'QP': reason = `Reactionary Delay to "P" coded Possession`;
                break;
      case'QT': reason = `Delay accepted by Network Rail as part of a commercial agreement where no substantive delay reason is identified`;
                break;
      case'R1': reason = `Incorrect train dispatch by station staff`;
                break;
      case'R2': reason = `Late TRTS given by station staff`;
                break;
      case'R3': reason = `Station staff unavailable - missing or uncovered`;
                break;
      case'R4': reason = `Station staff split responsibility - unable to cover all duties`;
                break;
      case'R5': reason = `Station staff error - e.g. wrong announcements, misdirection`;
                break;
      case'R7': reason = `Station delays due to special events e.g. sports fixtures`;
                break;
      case'R8': reason = `Delay at Station believed to be Operator cause and information required from Operator (Station Responsibility)`;
                break;
      case'RB': reason = `Passengers joining/alighting`;
                break;
      case'RC': reason = `Pre-booked assistance for a person with reduced mobility joining/alighting`;
                break;
      case'RD': reason = `Attaching/detaching/shunter/watering`;
                break;
      case'RE': reason = `Lift/escalator defect/failure`;
                break;
      case'RH': reason = `Station evacuated due to fire alarm`;
                break;
      case'RI': reason = `Waiting connections - not authorised by TOC Control`;
                break;
      case'RJ': reason = `Special Stop Orders - not authorised by TOC Control`;
                break;
      case'RK': reason = `Waiting passenger connections authorised by TOC but outwith TOC/Network Rail connection policy`;
                break;
      case'RL': reason = `Special Stop Orders authorised by TOC Control (including any delay at point of issue)`;
                break;
      case'RM': reason = `Waiting connections from other transport modes`;
                break;
      case'RN': reason = `Passengers "forcing" connections between trains outside connectional allowances`;
                break;
      case'RO': reason = `Passengers taken ill on platform`;
                break;
      case'RP': reason = `Passenger dropped object whilst boarding/alighting from train and train delayed at TOC request`;
                break;
      case'RQ': reason = `Un-booked assistance for a person with reduced mobility joining/alighting`;
                break;
      case'RR': reason = `Loading or unloading reserved bicycles`;
                break;
      case'RS': reason = `Loading or unloading unreserved bicycles`;
                break;
      case'RT': reason = `Loading excessive luggage`;
                break;
      case'RU': reason = `Locating lost luggage`;
                break;
      case'RV': reason = `Customer Information System failure`;
                break;
      case'RW': reason = `Station flooding (including issues with drains) not the result of weather, where the water has not emanated from Network Rail maintained infrastructure/network`;
                break;
      case'RY': reason = `Mishap - Station Operator cause`;
                break;
      case'RZ': reason = `Other Station Operator causes`;
                break;
      case'T2': reason = `Delay at unstaffed station to non-DOO train`;
                break;
      case'T3': reason = `Waiting connections from other transport modes`;
                break;
      case'T4': reason = `Loading Supplies (including catering)`;
                break;
      case'T8': reason = `Delay at Station believed to be Operator cause and information required from Operator (Ops Responsibility)`;
                break;
      case'TA': reason = `Train-crew/loco/stock/unit diagram issues`;
                break;
      case'TB': reason = `Train cancelled/delayed at Train Operator's request`;
                break;
      case'TC': reason = `Booked Traincrew used for additional/other service`;
                break;
      case'TD': reason = `Booked loco/stock/unit used for additional/other service`;
                break;
      case'TE': reason = `Injury to passenger on train`;
                break;
      case'TF': reason = `Seat reservation problems`;
                break;
      case'TG': reason = `Driver`;
                break;
      case'TH': reason = `(Senior) Conductor/Train Manager`;
                break;
      case'TI': reason = `Traincrew rostering problem`;
                break;
      case'TJ': reason = `Tail lamp or headlamp missing, not lit or wrongly displayed`;
                break;
      case'TK': reason = `Train catering staff (including Contractors)`;
                break;
      case'TM': reason = `Connection authorised by TOC but outwith connection policy`;
                break;
      case'TN': reason = `Late presentation from the continent`;
                break;
      case'TO': reason = `Time lost en-route believed to be Operator cause and information required from Operator (Ops Responsibility)`;
                break;
      case'TP': reason = `Special Stop Orders`;
                break;
      case'TR': reason = `Train Operating Company Directive`;
                break;
      case'TS': reason = `Delay due to incorrect ETCS system or equipment operation by Driver`;
                break;
      case'TT': reason = `Autumn-attribution Neutral Zone delays (See Supplementary Autumn Attribution Guidance)`;
                break;
      case'TW': reason = `Driver adhering to company professional driving standards or policy`;
                break;
      case'TX': reason = `Delays incurred on non-Network Rail running lines including London Underground causes (except T&RS)`;
                break;
      case'TY': reason = `Mishap-Train Operating Company cause`;
                break;
      case'TZ': reason = `Other Passenger Train Operating Company causes`;
                break;
      case'V8': reason = `Train striking bird (pheasant or smaller)`;
                break;
      case'VA': reason = `Disorder/drunks/trespass etc`;
                break;
      case'VB': reason = `Vandalism/theft`;
                break;
      case'VC': reason = `Fatalities/injuries sustained whilst on a platform as the result of being struck by a train or falling from a train`;
                break;
      case'VD': reason = `Passenger taken ill on train`;
                break;
      case'VE': reason = `Ticket irregularities/refusals to pay`;
                break;
      case'VF': reason = `Fire caused by vandalism`;
                break;
      case'VG': reason = `Police searching train`;
                break;
      case'VH': reason = `Communication cord or emergency train alarm operated`;
                break;
      case'VI': reason = `Security alert affecting stations and depots`;
                break;
      case'VR': reason = `Driver adhering to company professional driving standards or policies during severe weather conditions that are not fleet related`;
                break;
      case'VW': reason = `Severe weather affecting passenger fleet equipment including following company standards/policies or Rule Book instructions`;
                break;
      case'VX': reason = `Passenger charter excludable events occurring on the LUL or other non NR running lines`;
                break;
      case'VZ': reason = `Other passenger or external causes the responsibility of TOC`;
                break;
      case'X1': reason = `Visibility in semaphore signalled areas, or special working for fog and falling snow implemented by Network Rail - in all signalling areas`;
                break;
      case'X2': reason = `Severe flooding beyond that which could be mitigated on Network Rail infrastructure`;
                break;
      case'X3': reason = `Lightning Strike - damage to protected systems.`;
                break;
      case'X4': reason = `Blanket speed restriction for extreme heat or high wind in accordance with the Group Standards`;
                break;
      case'X8': reason = `Animal Strike/Incursion not within the control of Network Rail`;
                break;
      case'X9': reason = `Points failure caused by severe snow where heaters are working as designed`;
                break;
      case'XA': reason = `Trespass (Including non-intentional)`;
                break;
      case'XB': reason = `Vandalism/theft (including the placing of objects on the line)`;
                break;
      case'XC': reason = `Fatalities or injuries caused by being hit by train (Including non-intentional)`;
                break;
      case'XD': reason = `Level Crossing Incidents`;
                break;
      case'XF': reason = `Police searching line`;
                break;
      case'XH': reason = `Severe heat affecting infrastructure the responsibility of Network Rail (excluding Heat speeds)`;
                break;
      case'XI': reason = `Security alert affecting Network Rail Network`;
                break;
      case'XK': reason = `External Power Supply Failure Network Rail Infrastructure`;
                break;
      case'XL': reason = `Fire external to railway infrastructure`;
                break;
      case'XM': reason = `Gas/water mains/overhead power lines`;
                break;
      case'XN': reason = `Road related - excl bridge strikes/level crossing incident`;
                break;
      case'XO': reason = `External trees, building or objects encroaching onto Network Rail infrastructure (not due to weather or vandalism)`;
                break;
      case'XP': reason = `Bridge Strike`;
                break;
      case'XQ': reason = `Swing bridge open for river or canal traffic`;
                break;
      case'XR': reason = `Cable vandalism or theft`;
                break;
      case'XT': reason = `Severe cold weather affecting infrastructure the responsibility of Network Rail`;
                break;
      case'XU': reason = `Sunlight on signal or dispatch equipment where all reasonable mitigation has been taken`;
                break;
      case'XV': reason = `Fire or evacuation due to fire alarm of Network Rail buildings due to vandalism (not including stations)`;
                break;
      case'XW': reason = `High winds affecting infrastructure the responsibility of Network Rail including objects on the line due to the effect of weather`;
                break;
      case'XZ': reason = `Other external causes the responsibility of Network Rail`;
                break;
      case'YA': reason = `Lost path - regulated for train running less late`;
                break;
      case'YB': reason = `Lost path - regulated for another late running train`;
                break;
      case'YC': reason = `Lost path - following train running less late`;
                break;
      case'YD': reason = `Lost path - following another late running train`;
                break;
      case'YE': reason = `Waiting to/from single line`;
                break;
      case'YG': reason = `Regulated in accordance with Regulation Policy`;
                break;
      case'YI': reason = `Late arrival of booked inward stock`;
                break;
      case'YJ': reason = `Late arrival of booked Traincrew`;
                break;
      case'YK': reason = `Waiting connecting Freight or Res traffic to attach`;
                break;
      case'YL': reason = `Waiting passenger connections within connections policy, contingency plan or otherwise agreed by NR/TOC`;
                break;
      case'YM': reason = `Special stop orders within the contingency plan or agreed by NR/TOC`;
                break;
      case'YN': reason = `Service Recovery- booked train crew, not available`;
                break;
      case'YO': reason = `Waiting platform/station congestion/platform alteration`;
                break;
      case'YP': reason = `Delays due to diversions from booked route or line`;
                break;
      case'YQ': reason = `Passenger overcrowding caused by a train being of short formation`;
                break;
      case'YR': reason = `Tactical cancellation for service recovery not caused by late running`;
                break;
      case'YT': reason = `Reactionary delay to a train that is not leaving the network, by a train that is leaving the network`;
                break;
      case'YU': reason = `Service Recovery - booked rolling stock, not available`;
                break;
      case'YX': reason = `Passenger overcrowding caused by delay or cancellation of another train or its own late running`;
                break;
      case'ZW': reason = `Uninvestigated Cancellations System Roll-Ups only`;
                break;
      case'ZS': reason = `No cause ascertainable for a Sub Threshold Delay causing Threshold Reactionary (where agreed by both Parties)`;
                break;
      case'ZU': reason = `No Cause Identified After Full Investigation by Both Parties (A ‘Full Investigation’ will be one including all avenues of investigation agreed as reasonable by both Parties)`;
                break;
      case'ZX': reason = `Uninvestigated Late Start System Roll-Ups only`;
                break;
      case'ZY': reason = `Uninvestigated Station Overtime System Roll-Up only`;
                break;
      case'ZZ': reason = `Uninvestigated Loss in Running System Roll-Up only`;
                break;
    }

    return reason;
  }

}
